[[pft]]
a_hd = 116.0
ca_ratio = 390.43
f_g = 0.02
h_max = 25.33
lai = 1.8
m = 2
n = 5
name = 'test1'
par_ext = 0.5
resp_f = 0.1
resp_r = 0.913
resp_s = 0.044
rho_s = 200.0
sla = 14.0
tau_f = 4.0
tau_r = 1.04
yld = 0.17
zeta = 0.17

[[pft]]
a_hd = 116.0
ca_ratio = 390.43
f_g = 0.02
h_max = 15.33
lai = 1.8
m = 2
n = 5
name = 'test2'
par_ext = 0.5
resp_f = 0.1
resp_r = 0.913
resp_s = 0.044
rho_s = 200.0
sla = 14.0
tau_f = 4.0
tau_r = 1.04
yld = 0.17
zeta = 0.17
