name: QA and Build

on: [push, pull_request, release]

jobs:

  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.2

  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Test with pytest
        shell: bash
        run: |
          pytest
      - name: Test with doctest (but not on Windows)
        # The path names in doctest warnings are OS specific so fail on Windows.
        # "Fixing" this requires editing __init__.py so that
        # warnings.formatwarning returns OS insensitive pathnames. Nope.
        shell: bash
        run: |
          python -m doctest pyrealm/*.py
        if: runner.os != 'Windows'
