name: Test and build

on: [push, pull_request, release]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.0

  test:
    needs: qa
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.9" , "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.1.6
      with:
        poetry-version: 1.2.2

    - name: Install dependencies
      run: poetry install

    - name: Run tests
      run: poetry run pytest -m "not profiling" --cov-report xml

    - name: Upload coverage reports to Codecov
      id: codecov
      if: success() && (matrix.os == 'ubuntu-latest' && matrix.python-version == 3.9)
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Setup Git LFS
      id: lfs
      if: steps.codecov.outcome == 'success' && github.ref == 'refs/heads/develop' &&
        github.event_name == 'pull_request' && (github.event.action == 'ready_for_review' ||
        github.event.action == 'closed' && github.event.pull_request.merged) ||
        github.event_name == 'push'
      run: |
        git lfs pull
        git lfs ls-files -n | xargs git lfs track
        git add .gitattributes

    - name: Run profiling
      id: profiling
      if: steps.lfs.outcome == 'success'
      run: |
        sudo apt-get install graphviz
        poetry run pytest -m "profiling" --profile-svg

    - name: Generate report
      continue-on-error: true
      run: poetry run python profiling/report.py --event ${{ github.event_name }}

    - uses: stefanzweifel/git-auto-commit-action@v5
      id: commit
      if: ${{ steps.profiling.outcome != 'skipped' }}
      with:
        commit_message: Auto-generated profiling results
        file_pattern: 'profiling/*'

    - name: Create a new PR adding profiling results
      if: steps.commit.outcome == 'success' && github.event.action == 'closed'
      run: gh pr create --base "develop" --title "Auto-generated profiling report" --body "New profiling results available in the `profiling` folder."
      env:
        GH_TOKEN: ${{ github.token }}

  docs_build:
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.2.2

      - name: Install dependencies
        run: poetry install

      - name: Set ipython kernel
        run: poetry run python -m ipykernel install --user --name=pyrealm_python3
      
      - name: Build docs using sphinx
        run: |
          cd docs
          poetry run sphinx-build -W --keep-going source build

      - name: Archive built docs for error checking on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: built-docs
          path: docs/build
          retention-days: 2
